### ISSUE TITLE
Swipe issue in Mobile View

### ISSUE THREAD

**Issue by bhaveshpawar** [pizza3/re-swipe#1]
All functions work properly in web browser(desktop) , but while on mobile left swipe doesn't work. Even after swiping to left the div is swiped to right.

**Comment by pizza3** [comment]
Hey @bhaveshpawar ,
can you please reproduce this issue on a codesandbox or codepen, It would be pretty helpful, 
also which mobile browser and mobile OS you were using.

**Comment by pizza3** [comment]
Oh i see, it was because of the `screenX` and `screenY` , sorry my bad 😓.
